### ISSUE TITLE
Add some case, from Parcs Test Suite as a test.

### ISSUE THREAD

**Issue by hmarrao** [nfqsolutions/nfq-xfp#3]
At PARCS developers [page](https://engineering.purdue.edu/PARCS/Code/TestSuite/CalculationMode/StandAloneMode)

there some cases that one can execute and upload the bpf file generated.

It would be cool to add this case as a unittest and also as a notebook for a Getting Started Example o similar.

**Comment by ivanbenas** [comment]
We get a generic bpf file from https://engineering.purdue.edu/PARCS/Code/TestSuite to test PARCS graph files.
It was included in test folder
